### ISSUE TITLE
Play Again ship & captain name input screen layout broken

### ISSUE THREAD

**Issue by ghost** [SWThurlow/mars-mission-gamejam#32]
![Screenshot 2021-08-06 at 07 31 28](https://user-images.githubusercontent.com/10727296/128466609-fd640794-7ade-4a35-921e-4d0ef8b28ca0.png)

When clicking play again the inputs for captain and ship name are partially off the game area and layout broken. Game cannot be played again from this screen. Home and Play Now still available from top menu.

Probably best solved by whoever set up the grid layout.

**Comment by SWThurlow** [comment]
I forgot to remove the landing class from the game play div. This shouldn't be an issue now.
