### ISSUE TITLE
Add player name and ship name

### ISSUE THREAD

**Issue by ghost** [SWThurlow/mars-mission-gamejam#7]
I'm thinking we could ask the player for their name at the start and ask them to name the ship. Then at the end of the game we can congratulate them on getting their ship to mars, or say Ohh No! The ${shipName} has ran out of fuel! Don't worry Captain ${playerName} they'll be able to get us back to earth thenwe can try again.

https://discord.com/channels/847716020566622228/855005436573777940/865506848241352715

**Comment by SWThurlow** [comment]
I  have added getting the players name and ship name at the start. I will create a separate  issue for adding them to the end game messages.
